services:
  app:
    build:
      context: ./gerenciador-pautas
      dockerfile: app.dockerfile
    image: "gerenciador_pauta_app"
    container_name: ${APP_CONTAINER_NAME}
    depends_on:
      - ${PG_CONTAINER_NAME}
    ports:
      - "8080:8080"
    networks:
      - commons-api
    links:
      - postgres
  postgres:
    build:
      context: ./postgres
      dockerfile: postgres.dockerfile
    image: "postgres-pauta"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - dbp:/data/gerenciador_pautas_db
    ports:
      - "5432:5432"
    networks:
      - commons-api
    restart: unless-stopped
volumes:
  dbp:
    external: false

networks:
  commons-api:
    driver: bridge
