services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres-pauta"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - dbp:/data/gerenciador_pautas_db
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  dbp:
    external: false
